task: building_class

model:
  model_id: google/paligemma2-3b-pt-448
  adapter_id: /content/drive/MyDrive/models/pg2-3b-pt-448.adaptive-640/final
  processor_id: /content/drive/MyDrive/models/pg2-3b-pt-448.adaptive-640/final
  torch_dtype: bfloat16
  device_map: auto

base_dir: /content/drive/MyDrive/datasets/adaptive_640

data:
  train_jsonl: train.jsonl
  val_jsonl: val.jsonl
  test_jsonl: test.jsonl
  predict_jsonl: null
  image_root: .
  max_records: null

generation:
  output_jsonl: outputs/predict/building_class/fixed_640/pg2-3b-pt-448_cls5_r16_lr3e-5_s42/checkpoint-final/predictions.jsonl
  max_new_tokens: 16
  do_sample: false
  temperature: null
  top_p: null
  num_beams: 1
