task: building_class

model:
  model_id: google/paligemma2-3b-pt-224
  adapter_id: /content/drive/MyDrive/models/pg2-3b-pt-224.adaptive-640/final
  processor_id: /content/drive/MyDrive/models/pg2-3b-pt-224.adaptive-640/final
  torch_dtype: bfloat16
  device_map: auto

base_dir: /content/drive/MyDrive/datasets/adaptive_640

data:
  train_jsonl: train.jsonl
  val_jsonl: val.jsonl
  test_jsonl: test.jsonl
  predict_jsonl: null
  image_root: .
  max_records: null

generation:
  output_jsonl: "outputs/predict/building_class/adaptive_640/pg2-3b-pt-224__lora/predictions.jsonl"
  max_new_tokens: 16
  do_sample: false
  temperature: null
  top_p: null
  num_beams: 1
