nuts:
  enabled: true
  out_dir: data/raw/nuts
  url: https://gisco-services.ec.europa.eu/distribution/v2/nuts/geojson/NUTS_RG_01M_2024_4326_LEVL_2.geojson

eubucco:
  enabled: true
  out_dir: data/raw/eubucco
  version: v0.2
  nuts_ids:
    - DE21 # Oberbayern
    # - DE22 # Niederbayern
    # - DE23 # Oberpfalz
    # - DE24 # Oberfranken
    # - DE25 # Mittelfranken
    # - DE26 # Unterfranken
    # - DE27 # Schwaben

bayern:
  enabled: true
  out_dir: data/raw/bayern/dop20
  meta4_urls:
    # - https://geodaten.bayern.de/odd/a/dop20/meta/metalink/09161000.meta4 # Ingolstadt
    - https://geodaten.bayern.de/odd/a/dop20/meta/metalink/09162000.meta4 # München
    # - https://geodaten.bayern.de/odd/a/dop20/meta/metalink/09163000.meta4 # Rosenheim
    # - https://geodaten.bayern.de/odd/a/dop20/meta/metalink/09761000.meta4 # Augsburg

download:
  overwrite: false
  timeout_seconds: 60
  max_workers: 8
  show_progress: true
